### ISSUE TITLE
Semicolon ?

### ISSUE THREAD

**Issue by JasimAlrawie** [pixelkind/p5notebook#2]
Errors:
Line 6, col 16: Missing semicolon.

why do i need semicolon in JavaScript strictly.

**Comment by pixelkind** [comment]
Sorry for the late reply. It is a mandatory thing currently in the linter I use. In the future version, I will add the possibility to change linter settings.

**Comment by JasimAlrawie** [comment]
> Sorry for the late reply. It is a mandatory thing currently in the linter I use. In the future version, I will add the possibility to change linter settings.

one year later, lol
